### ISSUE TITLE
Paclet server integration

### ISSUE THREAD

**Issue by b3m2a1** [jkuczm/MathematicaCellsToTeX#26]
I was wondering if you'd want to add your package to the [Paclet Server / Package Repo)](https://paclets.github.io/PacletServer/) I've set up for the general Mathematica community. Per [this](https://github.com/paclets/PacletServer/issues/35) I'm trying to increase awareness and get more paclets on the server so that more people can benefit from it.

I can handle any initial reformatting necessary to make everything work right, and I'll submit a pull request with any changes.

**Comment by jkuczm** [comment]
Issue: paclets/PacletServer/issues/45 opened.
